language: node_js
node_js:
  - 12
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $BLOG_TOKEN
  keep_history: true
  on:
    branch: master