language: node_js
node_js:
  - 12
install:
  - npm install
script:
  - npm run build
branches:
  only:
    - docs
after_success:
  - cd docs/.vuepress/dist
  - git init
  - git config --global user.name "${USER_NAME}"
  - git config --global user.email "${USER_EMAIL}"
  - git add -A
  - git commit -m 'deploy'
  - git push --quiet --force "https://${GITHUB_TOKEN}@${GITHUB_REF}" master:${GITHUB_BRANCH}